In [2]:
import os
import pandas as pd
from pathlib import Path
import numpy as np
import anndata
import time
import matplotlib.pyplot as plt
import json

from abc_atlas_access.abc_atlas_cache.abc_project_cache import AbcProjectCache

pd.set_option('display.max_columns', 500)

In [3]:
version = '20260711'
download_base = Path('../../data/allen-brain-cell-atlas-staging')
abc_cache = AbcProjectCache.from_cache_dir(
    download_base,
    s3_bucket='allen-brain-cell-atlas-staging',
    auth_required=True,
)

abc_cache.load_manifest(f'releases/{version}/manifest.json')

/Users/chris.morrison/src/abc_atlas_access/src/abc_atlas_access/abc_atlas_cache/cloud_cache.py:679: OutdatedManifestWarning: You are loading releases/20260131/manifest.json. A more up to date version of the dataset -- releases/20260711/manifest.json -- exists online. To see the changes between the two versions of the dataset, run
type.compare_manifests('releases/20260131/manifest.json', 'releases/20260711/manifest.json')
To load another version of the dataset, run
type.load_manifest('releases/20260711/manifest.json')
  warnings.warn(msg, OutdatedManifestWarning)

Read in the two DataFrames from the aging dataset we'll need to create an equivalent cluster annotation terms and term set like the WMB and WHB taxonomies.

In [4]:
taxonomy_dir = 'SEA-AD-Multiregion-taxonomy'

In [5]:
abc_cache.list_metadata_files(taxonomy_dir)

['cell_2d_embedding_coordinates',
 'cell_to_cluster_membership',
 'cluster',
 'cluster_annotation_term',
 'cluster_annotation_term_set',
 'cluster_to_cluster_annotation_membership']

In [6]:
term = abc_cache.get_metadata_dataframe(
    taxonomy_dir,
    'cluster_annotation_term'
)
term

cluster_annotation_term.csv: 100%|██████████| 32.3k/32.3k [00:00<00:00, 248kMB/s]

,label,name,cluster_annotation_term_set_label,cluster_annotation_term_set_name,color_hex_triplet,term_order,term_set_order,parent_term_label,parent_term_name,parent_term_set_label,CCN20230508_label
0,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,Class,#F05A28,1,0,NaN,NaN,NaN,NaN
1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,Class,#00ADF8,2,0,NaN,NaN,NaN,NaN
2,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,Class,#808080,3,0,NaN,NaN,NaN,NaN
3,CS20260630_SCLA_023,Astrocyte,CCN20260630_LEVEL_1,Subclass,#665C47,23,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN
4,CS20260630_SCLA_021,CA2-4,CCN20260630_LEVEL_1,Subclass,#D5BF41,21,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
234,CS20260630_SUPR_038,Vip_25-SEAAD,CCN20260630_LEVEL_2,Supertype,#492C56,38,2,CS20260630_SCLA_005,Vip,CCN20260630_LEVEL_1,NaN
235,CS20260630_SUPR_039,Vip_4,CCN20260630_LEVEL_2,Supertype,#D0AEDC,39,2,CS20260630_SCLA_005,Vip,CCN20260630_LEVEL_1,CS20230508_SUPT_0022
236,CS20260630_SUPR_040,Vip_5,CCN20260630_LEVEL_2,Supertype,#C7A5D3,40,2,CS20260630_SCLA_005,Vip,CCN20260630_LEVEL_1,CS20230508_SUPT_0023
237,CS20260630_SUPR_041,Vip_6,CCN20260630_LEVEL_2,Supertype,#BE9DCA,41,2,CS20260630_SCLA_005,Vip,CCN20260630_LEVEL_1,CS20230508_SUPT_0024
238,CS20260630_SUPR_042,Vip_9,CCN20260630_LEVEL_2,Supertype,#B494C1,42,2,CS20260630_SCLA_005,Vip,CCN20260630_LEVEL_1,CS20230508_SUPT_0025

In [7]:
term_sets = abc_cache.get_metadata_dataframe(
    directory=taxonomy_dir,
    file_name='cluster_annotation_term_set'
).set_index('label')
term_sets

cluster_annotation_term_set.csv:   0%|          | 0.00/208 [00:00<?, ?MB/s]

cluster_annotation_term_set.csv: 100%|██████████| 208/208 [00:00<00:00, 992MB/s]

                          name description  order parent_term_set_label
label
CCN20260630_LEVEL_0      Class       Class      0                   NaN
CCN20260630_LEVEL_1   Subclass    Subclass      1   CCN20260630_LEVEL_0
CCN20260630_LEVEL_2  Supertype   Supertype      2   CCN20260630_LEVEL_1

In [8]:
filtered = term[pd.notna(term['parent_term_label'])]
first_child = filtered.groupby('parent_term_label')[['label','name','term_order','cluster_annotation_term_set_name']].first()
first_child

,label,name,term_order,cluster_annotation_term_set_name
parent_term_label,,,,
CS20260630_CLAS_001,CS20260630_SCLA_009,Chandelier,9,Subclass
CS20260630_CLAS_002,CS20260630_SCLA_021,CA2-4,21,Subclass
CS20260630_CLAS_003,CS20260630_SCLA_023,Astrocyte,23,Subclass
CS20260630_SCLA_001,CS20260630_SUPR_001,Lamp5_Lhx6_1,1,Supertype
CS20260630_SCLA_002,CS20260630_SUPR_005,Lamp5_1,5,Supertype
CS20260630_SCLA_003,CS20260630_SUPR_011,Pax6_1,11,Supertype
CS20260630_SCLA_004,CS20260630_SUPR_018,Sncg_1,18,Supertype
CS20260630_SCLA_005,CS20260630_SUPR_025,Vip_1,25,Supertype
CS20260630_SCLA_006,CS20260630_SUPR_043,Sst Chodl_1,43,Supertype
CS20260630_SCLA_007,CS20260630_SUPR_048,Sst_1,48,Supertype
CS20260630_SCLA_008,CS20260630_SUPR_067,Pvalb_1,67,Supertype
CS20260630_SCLA_009,CS20260630_SUPR_082,Chandelier_1,82,Supertype
CS20260630_SCLA_010,CS20260630_SUPR_084,L2/3 IT_1,84,Supertype
CS20260630_SCLA_011,CS20260630_SUPR_095,L4 IT_1,95,Supertype
CS20260630_SCLA_012,CS20260630_SUPR_103,L5 IT_1,103,Supertype
CS20260630_SCLA_013,CS20260630_SUPR_112,L6 IT_1,112,Supertype
CS20260630_SCLA_014,CS20260630_SUPR_120,L6 IT Car3_1,120,Supertype
CS20260630_SCLA_015,CS20260630_SUPR_125,L5 ET_1,125,Supertype
CS20260630_SCLA_016,CS20260630_SUPR_131,L6 CT_1,131,Supertype
CS20260630_SCLA_017,CS20260630_SUPR_141,L6b_1,141,Supertype
CS20260630_SCLA_018,CS20260630_SUPR_150,L5/6 NP_1,150,Supertype
CS20260630_SCLA_019,CS20260630_SUPR_158,EC IT_1,158,Supertype
CS20260630_SCLA_020,CS20260630_SUPR_166,CA1_1,166,Supertype
CS20260630_SCLA_021,CS20260630_SUPR_169,CA2-3_1,169,Supertype
CS20260630_SCLA_022,CS20260630_SUPR_173,DG_1,173,Supertype
CS20260630_SCLA_023,CS20260630_SUPR_175,Astro_1,175,Supertype
CS20260630_SCLA_024,CS20260630_SUPR_181,Ependymal_1-SEAAD,181,Supertype
CS20260630_SCLA_025,CS20260630_SUPR_182,OPC_1,182,Supertype
CS20260630_SCLA_026,CS20260630_SUPR_186,Oligo_1,186,Supertype
CS20260630_SCLA_027,CS20260630_SUPR_192,Endo_1,192,Supertype
CS20260630_SCLA_028,CS20260630_SUPR_195,Pericyte_1,195,Supertype
CS20260630_SCLA_029,CS20260630_SUPR_200,Lymphocyte,200,Supertype

In [9]:
term.set_index('label',inplace=True)
term.loc[first_child.index,'first_child_label'] = first_child['label']
term.loc[first_child.index,'first_child_term_set_name'] = first_child['cluster_annotation_term_set_name']
term.reset_index(inplace=True)

In [10]:
term[pd.notna(term['first_child_label'])]

,label,name,cluster_annotation_term_set_label,cluster_annotation_term_set_name,color_hex_triplet,term_order,term_set_order,parent_term_label,parent_term_name,parent_term_set_label,CCN20230508_label,first_child_label,first_child_term_set_name
0,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,Class,#F05A28,1,0,NaN,NaN,NaN,NaN,CS20260630_SCLA_009,Subclass
1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,Class,#00ADF8,2,0,NaN,NaN,NaN,NaN,CS20260630_SCLA_021,Subclass
2,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,Class,#808080,3,0,NaN,NaN,NaN,NaN,CS20260630_SCLA_023,Subclass
3,CS20260630_SCLA_023,Astrocyte,CCN20260630_LEVEL_1,Subclass,#665C47,23,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_175,Supertype
4,CS20260630_SCLA_021,CA2-4,CCN20260630_LEVEL_1,Subclass,#D5BF41,21,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_169,Supertype
5,CS20260630_SCLA_009,Chandelier,CCN20260630_LEVEL_1,Subclass,#F641A8,9,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_082,Supertype
6,CS20260630_SCLA_022,DG,CCN20260630_LEVEL_1,Subclass,#D8442B,22,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_173,Supertype
7,CS20260630_SCLA_019,EC IT,CCN20260630_LEVEL_1,Subclass,#73BC48,19,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_158,Supertype
8,CS20260630_SCLA_027,Endothelial,CCN20260630_LEVEL_1,Subclass,#8D6C62,27,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_192,Supertype
9,CS20260630_SCLA_024,Ependymal,CCN20260630_LEVEL_1,Subclass,#7A5151,24,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_181,Supertype
10,CS20260630_SCLA_029,Immune,CCN20260630_LEVEL_1,Subclass,#94AF97,29,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_200,Supertype
11,CS20260630_SCLA_010,L2/3 IT,CCN20260630_LEVEL_1,Subclass,#B1EC30,10,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_084,Supertype
12,CS20260630_SCLA_011,L4 IT,CCN20260630_LEVEL_1,Subclass,#00E5E5,11,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_095,Supertype
13,CS20260630_SCLA_015,L5 ET,CCN20260630_LEVEL_1,Subclass,#0D5B78,15,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_125,Supertype
14,CS20260630_SCLA_012,L5 IT,CCN20260630_LEVEL_1,Subclass,#50B2AD,12,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_103,Supertype
15,CS20260630_SCLA_018,L5/6 NP,CCN20260630_LEVEL_1,Subclass,#3E9E64,18,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_150,Supertype
16,CS20260630_SCLA_016,L6 CT,CCN20260630_LEVEL_1,Subclass,#2D8CB8,16,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_131,Supertype
17,CS20260630_SCLA_013,L6 IT,CCN20260630_LEVEL_1,Subclass,#A19922,13,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_112,Supertype
18,CS20260630_SCLA_014,L6 IT Car3,CCN20260630_LEVEL_1,Subclass,#5100FF,14,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_120,Supertype
19,CS20260630_SCLA_017,L6b,CCN20260630_LEVEL_1,Subclass,#7044AA,17,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_141,Supertype
20,CS20260630_SCLA_002,Lamp5,CCN20260630_LEVEL_1,Subclass,#DA808C,2,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_005,Supertype
21,CS20260630_SCLA_001,Lamp5 Lhx6,CCN20260630_LEVEL_1,Subclass,#935F50,1,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_001,Supertype
22,CS20260630_SCLA_025,OPC,CCN20260630_LEVEL_1,Subclass,#374A45,25,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_182,Supertype
23,CS20260630_SCLA_026,Oligodendrocyte,CCN20260630_LEVEL_1,Subclass,#53776C,26,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_186,Supertype
24,CS20260630_SCLA_003,Pax6,CCN20260630_LEVEL_1,Subclass,#71238C,3,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_011,Supertype
25,CS20260630_SCLA_008,Pvalb,CCN20260630_LEVEL_1,Subclass,#D93137,8,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_067,Supertype
26,CS20260630_SCLA_004,Sncg,CCN20260630_LEVEL_1,Subclass,#DF70FF,4,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_018,Supertype
27,CS20260630_SCLA_007,Sst,CCN20260630_LEVEL_1,Subclass,#FF9900,7,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_048,Supertype
28,CS20260630_SCLA_006,Sst Chodl,CCN20260630_LEVEL_1,Subclass,#B1B10C,6,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_043,Supertype
29,CS20260630_SCLA_020,Sub-CA1,CCN20260630_LEVEL_1,Subclass,#DECB54,20,1,CS20260630_CLAS_002,Neuronal: Glutamatergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_166,Supertype
30,CS20260630_SCLA_028,VLMC & Perivascular,CCN20260630_LEVEL_1,Subclass,#697255,28,1,CS20260630_CLAS_003,Non-neuronal and Non-neural,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_195,Supertype
31,CS20260630_SCLA_005,Vip,CCN20260630_LEVEL_1,Subclass,#A45FBF,5,1,CS20260630_CLAS_001,Neuronal: GABAergic,CCN20260630_LEVEL_0,NaN,CS20260630_SUPR_025,Supertype

In [13]:
membership = abc_cache.get_metadata_dataframe(directory=taxonomy_dir, file_name='cluster_to_cluster_annotation_membership')
pivot = membership.groupby(['cluster_alias', 'cluster_annotation_term_set_name'])['cluster_annotation_term_name'].first().unstack()
pivot = pivot[term_sets['name']] # order columns
pivot.fillna('Other', inplace=True)
pivot.sort_values(['Class', 'Subclass', 'Supertype'], inplace=True)
cols = pivot.columns.to_list()
pivot.columns = cols
pivot

,Class,Subclass,Supertype
cluster_alias,,,
82,Neuronal: GABAergic,Chandelier,Chandelier_1
83,Neuronal: GABAergic,Chandelier,Chandelier_2
5,Neuronal: GABAergic,Lamp5,Lamp5_1
6,Neuronal: GABAergic,Lamp5,Lamp5_2
7,Neuronal: GABAergic,Lamp5,Lamp5_3
...,...,...,...
195,Non-neuronal and Non-neural,VLMC & Perivascular,Pericyte_1
196,Non-neuronal and Non-neural,VLMC & Perivascular,Pericyte_2-SEAAD
197,Non-neuronal and Non-neural,VLMC & Perivascular,SMC-SEAAD
198,Non-neuronal and Non-neural,VLMC & Perivascular,VLMC_1
199,Non-neuronal and Non-neural,VLMC & Perivascular,VLMC_2-SEAAD

In [14]:
lookup = {}
for tag in term_sets['name']:
    #print(tag)
    pred = (term['cluster_annotation_term_set_name'] == tag)
    filtered = term[pred].copy()
    filtered.set_index('name', inplace=True)
    lookup[tag] = filtered

Helper functions to lookup an term attribut and format a cell in the html table

In [15]:
def get_value(c, n, v) :
    return lookup[c].loc[n][v]

def format_cell (df,c,add_id=False,add_plus=False,add_minus=False) :

    divs = pd.DataFrame(index=df.index)
    
    pattern = '<div class="circle" style="background-color:%s"></div>'
    divs['circle'] = [pattern % get_value(c,x,'color_hex_triplet') for x in df[c]]
    
    pattern = '<div class="celltext">%s</div>'
    divs['name'] = [pattern % x for x in df[c]]
   
    divs['id'] = ''
    if add_id :
        pattern = '<div id="%s"></div>'
        divs['id'] = [pattern % get_value(c,x,'label') for x in df[c]]
        
    divs['plus'] = ''
    if add_plus :
        pattern = '<div class="celltext"><a href="%s.html#%s">[+]</a></div>'
        divs['plus'] = [pattern % (get_value(c,x,'first_child_term_set_name'),
                                   get_value(c,x,'first_child_label')) for x in df[c]]
        
    divs['minus'] = ''
    if add_minus :
        pattern = '<div class="celltext"><a href="%s.html#%s">[-]</a></div>'
        divs['minus'] = [pattern % (get_value(c,x,'cluster_annotation_term_set_name'),
                                    get_value(c,x,'label')) for x in df[c]]
    
    cols = ['id','circle','name','plus','minus']
    output = divs[cols].apply(lambda row: ''.join(row.values.astype(str)), axis=1)
    return output

Helper function to create html document

In [16]:
def create_html(df, ts, file, title):
    
    # apply formatter to each term set
    df_formatted = df.copy()
    
    for tag in term_sets['name'] :
        if tag in df_formatted.columns :

            add_id = False
            if tag == ts :
                add_id = True
                
            add_plus = False
            if tag == ts and tag not in ['Supertype']:
                add_plus = True
                
            add_minus = False
            if tag != ts and tag not in ['']:
                add_minus = True
                
            df_formatted[tag] = format_cell(df,tag,add_id,add_plus,add_minus)
            
            
    output = df_formatted.to_html(index=False, na_rep='',
                        render_links=True,escape=False,
                        classes="mystyle")

    html_string = '''
    <html>
    <head><title>%s</title></head>
    <link rel="stylesheet" type="text/css" href="../../simple_style.css"/>
    <body>
    {table}
    </body>
    </html>.
    ''' % title

    # OUTPUT AN HTML FILE
    with open(file, 'w') as f:
        f.write(html_string.format(table=output))

In [17]:
# Write the data to the _static directory of the abc_atlas_access so that links work properly in the jupyter-book/sphinx page.
output_directory = os.path.join('../../_static', taxonomy_dir, version)
os.makedirs(output_directory, exist_ok=True)

In [18]:
df_supertype = pivot[['Class']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory, 'class.html')
title = 'SEA-AD Multiregion taxonomy: Class'
create_html(df_supertype, 'Class', file, title)
print(len(df_supertype))

3

In [19]:
df_supertype = pivot[['Class', 'Subclass']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory, 'subclass.html')
title = 'SEA-AD Multiregion taxonomy: Subclass'
create_html(df_supertype, 'Subclass', file, title)
print(len(df_supertype))

29

In [20]:
df_supertype = pivot[['Class', 'Subclass', 'Supertype']].copy()
df_supertype.drop_duplicates(inplace=True)

file = os.path.join(output_directory, 'supertype.html')
title = 'SEA-AD Multiregion taxonomy: Supertype'
create_html(df_supertype, 'Supertype', file, title)
print(len(df_supertype))

207